#!/usr/bin/env python3
"""
Build the html_to_apk.apk — the WebView wrapper that loads our English UI
and connects to the cloud backend.

Pipeline (pure-Android, no Gradle):
  aapt2 compile  →  aapt2 link  →  javac  →  d8  →  inject dex  →  apksigner

This is the same toolchain the backend uses to build per-function APKs,
so the output is byte-for-byte similar to what users will get from builds.
"""
import os, sys, shutil, subprocess, zipfile, hashlib, struct, zlib
from pathlib import Path

# Paths
ROOT = Path("/home/z/my-project/html_to_apk")
ANDROID_DIR = ROOT / "android"
SRC = ANDROID_DIR / "app" / "src" / "main"
TOOLS = ROOT / "backend" / "build_tools"
AAPT2 = TOOLS / "aapt2"
D8_JAR = TOOLS / "d8.jar"
APKSIGNER_JAR = TOOLS / "apksigner-lib.jar"
ANDROID_JAR = TOOLS / "android.jar"
KEYSTORE = TOOLS / "debug.keystore"
KEYSTORE_ALIAS = "bardom-debug"
KEYSTORE_PASS = "bardom123"
JDK_BIN = "/home/z/my-project/jdk/jdk-21.0.5+11/bin"

# Output
WORK = ROOT / "_build_work"
OUT = ROOT / "download"
OUT.mkdir(parents=True, exist_ok=True)

# Backend URL (will be embedded in BuildConfig.java)
BACKEND_URL = os.environ.get("BACKEND_URL", "https://html-to-apk-1789777001.onrender.com")
APK_NAME = "html_to_apk.apk"
PACKAGE = "com.htmltoapk.main"
APP_NAME = "HTML to APK"
VERSION_CODE = 1
VERSION_NAME = "1.0.0"

# ─── helper ──────────────────────────────────────────────────────────────────
def zipalign(in_apk: Path, out_apk: Path, alignment: int = 4) -> None:
    """Binary-level zipalign — rewrites the ZIP so STORED entries are aligned.

    Python's zipfile module doesn't let us control local-header offsets
    reliably (it overwrites the extra field when committing entries),
    so we walk the binary ZIP format manually.

    MANDATORY before signing — Android 11+ silently rejects unaligned APKs
    with the misleading "App not installed" message.
    """
    sys.path.insert(0, str(Path(__file__).parent))
    from zipalign import zipalign as _zipalign_impl
    _zipalign_impl(in_apk, out_apk, alignment=alignment)

def run(cmd, cwd=None, timeout=180, env=None):
    e = dict(os.environ)
    if env: e.update(env)
    e["PATH"] = JDK_BIN + os.pathsep + e.get("PATH", "")
    e["JAVA_HOME"] = JDK_BIN.rsplit("/bin", 1)[0]
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout, env=e)
    if proc.returncode != 0:
        print(f"✗ Command failed: {' '.join(cmd[:6])}…", file=sys.stderr)
        print(f"  stdout: {proc.stdout[-2000:]}", file=sys.stderr)
        print(f"  stderr: {proc.stderr[-2000:]}", file=sys.stderr)
        sys.exit(1)
    return proc.stdout, proc.stderr

def write_icons(res_dir):
    """Generate launcher icons (PNG with colored circle)."""
    densities = {"mipmap-mdpi": 48, "mipmap-hdpi": 72, "mipmap-xhdpi": 96,
                 "mipmap-xxhdpi": 144, "mipmap-xxxhdpi": 192}
    seed = "html_to_apk_main_app"
    h = hashlib.md5(seed.encode()).digest()
    r, g, b = min(255, h[0] + 60), min(255, h[1] + 60), min(255, h[2] + 60)

    def make_png(size):
        def chunk(t, d):
            c = t + d
            return struct.pack(">I", len(d)) + c + struct.pack(">I", zlib.crc32(c) & 0xffffffff)
        sig = b"\x89PNG\r\n\x1a\n"
        ihdr = chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
        raw = bytearray()
        cx = cy = size // 2
        radius = int(size * 0.36)
        for y in range(size):
            raw.append(0)
            for x in range(size):
                if ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5 < radius:
                    raw.extend([255, 255, 255])
                else:
                    raw.extend([r, g, b])
        idat = chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        iend = chunk(b"IEND", b"")
        return sig + ihdr + idat + iend

    for folder, size in densities.items():
        d = res_dir / folder
        d.mkdir(parents=True, exist_ok=True)
        (d / "ic_launcher.png").write_bytes(make_png(size))

def write_buildconfig(java_dir):
    """Write a BuildConfig.java with the backend URL."""
    pkg_dir = java_dir / PACKAGE.replace(".", "/")
    pkg_dir.mkdir(parents=True, exist_ok=True)
    src = f'''package {PACKAGE};

/**
 * Build-time constants for HTML to APK.
 * Generated by build_apk.py.
 */
public final class BuildConfig {{
    public static final String BACKEND_URL = "{BACKEND_URL}";
    public static final String VERSION_NAME = "{VERSION_NAME}";
    public static final int VERSION_CODE = {VERSION_CODE};
    public static final boolean DEBUG = false;
}}
'''
    (pkg_dir / "BuildConfig.java").write_text(src, encoding="utf-8")
    print(f"  ✓ Generated BuildConfig.java (backend={BACKEND_URL})")

# ─── main ─────────────────────────────────────────────────────────────────────
def main():
    print("╔════════════════════════════════════════════════════╗")
    print("║  Building html_to_apk.apk (pure-Android, no Gradle) ║")
    print("╚════════════════════════════════════════════════════╝")
    print(f"  Backend URL:  {BACKEND_URL}")
    print(f"  Package:      {PACKAGE}")
    print(f"  App name:     {APP_NAME}")
    print(f"  Version:      {VERSION_NAME} (code {VERSION_CODE})")
    print()

    # Reset work dir
    if WORK.exists():
        shutil.rmtree(WORK)
    WORK.mkdir(parents=True)

    project_dir = WORK / "project"
    src_main = project_dir / "src" / "main"
    res_dir = src_main / "res"
    java_dir = src_main / "java"
    assets_dir = src_main / "assets" / "webapp"
    build_dir = project_dir / "build"
    build_dir.mkdir(parents=True, exist_ok=True)

    # Copy source from android/app/src/main/
    print("[1/7] Staging source files…")
    if (SRC / "java").exists():
        shutil.copytree(SRC / "java", java_dir, dirs_exist_ok=True)
    if (SRC / "res").exists():
        shutil.copytree(SRC / "res", res_dir, dirs_exist_ok=True)
    if (SRC / "assets").exists():
        shutil.copytree(SRC / "assets", src_main / "assets", dirs_exist_ok=True)
    if (SRC / "AndroidManifest.xml").exists():
        shutil.copy2(SRC / "AndroidManifest.xml", src_main / "AndroidManifest.xml")
    # write_generated icons (overwrite if copied)
    write_icons(res_dir)
    write_buildconfig(java_dir)
    print("  ✓ Source staged")

    # 2) Compile resources
    print("[2/7] Compiling resources with aapt2…")
    compiled_zip = build_dir / "compiled.zip"
    res_files = [str(p) for p in sorted(res_dir.rglob("*")) if p.is_file()]
    run([str(AAPT2), "compile", "-o", str(compiled_zip)] + res_files, timeout=60)
    print(f"  ✓ {len(res_files)} resources compiled → {compiled_zip.name}")

    # 3) Link → APK skeleton
    print("[3/7] Linking APK skeleton with aapt2…")
    linked_apk = build_dir / "linked.apk"
    r_java_dir = build_dir / "gen" / PACKAGE.replace(".", "/")
    r_java_dir.mkdir(parents=True, exist_ok=True)
    manifest = src_main / "AndroidManifest.xml"
    assets = src_main / "assets"
    run([
        str(AAPT2), "link",
        "-o", str(linked_apk),
        "--manifest", str(manifest),
        "-I", str(ANDROID_JAR),
        "--min-sdk-version", "24",
        "--target-sdk-version", "34",
        "--version-code", str(VERSION_CODE),
        "--version-name", VERSION_NAME,
        "--rename-manifest-package", PACKAGE,
        "--auto-add-overlay",
        "-A", str(assets),
        "--java", str(r_java_dir.parent),
        str(compiled_zip),
    ], timeout=60)
    print(f"  ✓ Linked → {linked_apk.name}")

    # 4) Compile Java
    print("[4/7] Compiling Java sources with javac…")
    java_files = list(java_dir.rglob("*.java")) + list(build_dir.joinpath("gen").rglob("*.java"))
    classes_dir = build_dir / "classes"
    classes_dir.mkdir(parents=True, exist_ok=True)
    run([
        "javac", "-source", "17", "-target", "17",
        "-classpath", str(ANDROID_JAR),
        "-d", str(classes_dir),
    ] + [str(f) for f in java_files], timeout=60)
    print(f"  ✓ {len(java_files)} Java files compiled")

    # 5) d8 → classes.dex
    print("[5/7] Compiling .class → classes.dex with d8…")
    dex_dir = build_dir / "dex"
    dex_dir.mkdir(parents=True, exist_ok=True)
    class_files = list(classes_dir.rglob("*.class"))
    # IMPORTANT: d8 requires ALL .class files in the program (incl. R$xxx sub-classes
    # and inner classes). Passing a subset triggers "requires nest mates" errors.
    # Use a file-list approach via a @argfile to avoid command-line length limits.
    argfile = build_dir / "d8_argfile.txt"
    argfile.write_text("\n".join(str(f) for f in class_files), encoding="utf-8")
    run([
        "java", "-cp", str(D8_JAR),
        "com.android.tools.r8.D8",
        "--release", "--min-api", "24",
        "--output", str(dex_dir),
        "@" + str(argfile),
    ], timeout=120)
    dex_path = dex_dir / "classes.dex"
    if not dex_path.exists():
        print(f"✗ d8 did not produce classes.dex", file=sys.stderr)
        sys.exit(1)
    print(f"  ✓ {len(class_files)} class files → classes.dex ({dex_path.stat().st_size:,} bytes)")

    # 6) Inject classes.dex into APK
    print("[6/8] Injecting classes.dex into APK…")
    final_apk = OUT / APK_NAME
    shutil.copy2(linked_apk, final_apk)
    tmp = final_apk.parent / "tmp.apk"
    with zipfile.ZipFile(final_apk, "r") as src, \
         zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as dst:
        for item in src.infolist():
            if item.filename == "classes.dex":
                continue
            dst.writestr(item, src.read(item.filename))
        dst.write(dex_path, "classes.dex")
    tmp.replace(final_apk)
    print(f"  ✓ APK with dex → {final_apk.name} ({final_apk.stat().st_size:,} bytes)")

    # 7) zipalign (4-byte alignment) — MANDATORY before signing.
    # Android 11+ rejects unaligned APKs with "App not installed".
    print("[7/8] zipaligning APK (4-byte boundaries)…")
    aligned_apk = final_apk.parent / "tmp_aligned.apk"
    zipalign(final_apk, aligned_apk, alignment=4)
    shutil.copy2(aligned_apk, final_apk)
    aligned_apk.unlink()
    print(f"  ✓ Aligned → {final_apk.name}")

    # 8) Sign with apksigner
    print("[8/8] Signing APK with apksigner (v1+v2+v3)…")
    run([
        "java", "-jar", str(APKSIGNER_JAR), "sign",
        "--ks", str(KEYSTORE),
        "--ks-key-alias", KEYSTORE_ALIAS,
        "--ks-pass", f"pass:{KEYSTORE_PASS}",
        "--key-pass", f"pass:{KEYSTORE_PASS}",
        "--v1-signing-enabled", "true",
        "--v2-signing-enabled", "true",
        "--v3-signing-enabled", "true",
        "--v4-signing-enabled", "false",
        str(final_apk),
    ], timeout=120)
    # Verify
    out, _ = run([
        "java", "-jar", str(APKSIGNER_JAR), "verify", "--verbose", str(final_apk)
    ], timeout=60)
    print(f"  ✓ Signed & verified:")
    for line in out.splitlines()[:4]:
        print(f"      {line}")

    print()
    print("╔════════════════════════════════════════════════════╗")
    print(f"║  ✅ Built: {APK_NAME}")
    print(f"║  Path: {final_apk}")
    print(f"║  Size: {final_apk.stat().st_size:,} bytes ({final_apk.stat().st_size/1024:.1f} KB)")
    print("╚════════════════════════════════════════════════════╝")

if __name__ == "__main__":
    main()
